// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/techSphere.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
//         <mesh geometry={nodes.Sphere.geometry} material={materials.Retro} position={[-3.01, 0.89, 2.16]} rotation={[0, 0, 1.18]} />
//         <mesh geometry={nodes.mongoDBIcon.geometry} material={materials.Golem} position={[-33.32, -75.76, 119.34]} rotation={[1.21, -0.32, -0.07]} scale={0.28} />
//         <mesh geometry={nodes.nodeJsIcon.geometry} material={materials.Columbia} position={[-78.81, -31.95, 60.88]} rotation={[2.27, -1.02, 0.63]} scale={0.24} />
//         <mesh geometry={nodes.pNetIcon.geometry} material={materials['Day Dream']} position={[-3.33, 1.43, 2.16]} rotation={[-3.12, 0.04, -0.06]} scale={0.26} />
//         <mesh geometry={nodes.pythonIcon.geometry} material={materials.Nepal} position={[72.97, 29.5, 57]} rotation={[-2.39, 1.09, -2.37]} scale={[0.5, 0.5, 0.63]} />
//         <mesh geometry={nodes.reactIcon.geometry} material={materials.Ducati} position={[-6.53, 0.9, 177.39]} rotation={[0, -0.05, -0.01]} scale={0.29} />
//         <mesh geometry={nodes.htmlIcon.geometry} material={materials['Dust Storm']} position={[-79.36, 20.02, 128.11]} rotation={[-0.48, -1.07, -2.15]} scale={0.28} />
//         <mesh geometry={nodes.bootstrapIcon.geometry} material={materials['First Impression']} position={[69.17, -42, 114.93]} rotation={[0.96, 0.94, 0.48]} scale={0.27} />
//         <mesh geometry={nodes.cssIcon.geometry} material={materials.Fiji} position={[-47.94, 74.76, 76.41]} rotation={[-1.74, -0.53, 3.07]} scale={0.29} />
//         <mesh geometry={nodes.sasIcon.geometry} material={materials.Abstract} position={[31.69, 75.7, 119.11]} rotation={[-1.19, 0.41, -0.09]} scale={0.24} />
//         <mesh geometry={nodes.threeJsIcon.geometry} material={materials['Goodbye Mist']} position={[18.75, -82.5, 74.58]} rotation={[1.72, 0.24, 2.11]} scale={0.2} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/techSphere.gltf')
